SELECT * FROM PETRESCUE;

SELECT SUM(COST) SUM_OF_COST
FROM PETRESCUE;

SELECT MAX(QUANTITY) MAX_QUANTITY FROM PETRESCUE;

SELECT AVG(COST) AVG_COST_OF_ANIMALS
FROM PETRESCUE;

SELECT AVG(COST/QUANTITY)
FROM PETRESCUE
WHERE ANIMAL = 'Dog';

SELECT ROUND(COST)
FROM PETRESCUE;

SELECT ANIMAL, LENGTH(ANIMAL) LEN_OF_NAME
FROM PETRESCUE;

SELECT DISTINCT UPPER(ANIMAL)
FROM PETRESCUE;

SELECT *
FROM PETRESCUE 
WHERE LOWER(Animal) = 'cat';

SELECT MONTH(RESCUEDATE)
FROM PETRESCUE 
WHERE ANIMAL = 'Cat';

SELECT COUNT(*)
FROM PETRESCUE 
WHERE DAY(RESCUEDATE) = 14;

SELECT RESCUEDATE+3 FROM PETRESCUE;

select (CURRENT DATE - RESCUEDATE) from PETRESCUE;